version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: php-dev
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8.0.42
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
